#:tombi toml-version = "v1.0.0"

absolute-paths-max-segments = 3
inherent-impl-lint-scope = "module"

allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true

disallowed-macros = [
  { path = "std::assert_eq", reason = "use pretty_assertions::assert_eq instead" },
  { path = "std::assert_ne", reason = "use pretty_assertions::assert_ne instead" },
  { path = "core::assert_eq", reason = "use pretty_assertions::assert_eq instead" },
  { path = "core::assert_ne", reason = "use pretty_assertions::assert_ne instead" },
]
