#:schema https://json.schemastore.org/wranglerv3.json

name = "jpellis-me"
main = "build/index.js"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=jpellis-me worker-build --release --features ssr"

[assets]
directory = "./target/site"

[triggers]
crons = ["0 13 * * *", "0 13 * * 1"]

[[kv_namespaces]]
binding = "GITHUB_STATS"
id = "5e502e4bfb6b4f6985fcde597f6460e7"
preview_id = "4a22aeeb45134546ae5766655297f396"

[[kv_namespaces]]
binding = "WORK_STATS"
id = "a56dd2a711c746e8890f9bb9662131d6"
preview_id = "54f30bfa5bb44a33868229e83fd7b55b"

# Secret: run `wrangler secret put GITHUB_TOKEN` to set the GitHub PAT
