<script lang="ts">
  /**
   * The use of {@html } is safe here because the data is generated by the
   * server and is not user input.
   */

  /* eslint-disable svelte/no-at-html-tags */
  import type { PageData } from "./$types";

  // eslint-disable-next-line init-declarations
  export let data: PageData;
</script>

<h1 class="h1">Projects</h1>

<p class="text-xl lg:text-2xl">
  {#await data.github}
    I have a passion for open source software and have contributed to a number
    of projects. I have created 18 repositories on GitHub which have received
    286 stars and have been forked 47 times.
  {:then value}
    I have a passion for open source software and have contributed to a number
    of projects. I have created {value.repos} repositories on GitHub which have received
    {value.stars} stars and have been forked
    {value.forks} times.
  {:catch}
    I have a passion for open source software and have contributed to a number
    of projects. I have created 18 repositories on GitHub which have received
    286 stars and have been forked 47 times.
  {/await}
</p>

<div class="grid grid-cols-1 lg:grid-cols-2 grid-flow-row gap-10">
  {#each data.projects as { title, slug, blurb }}
    <a class="card p-4 variant-glass-primary" href="/projects/{slug}/">
      <header class="card-header">
        <h2 class="h2">{@html title}</h2>
      </header>
      <section class="p-4 flex flex-col gap-4">
        {@html blurb}
      </section>
    </a>
  {/each}
</div>
