name: Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  sync-labels:
    name: Synchronise labels

    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Synchronize labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2
        with:
          config-file: .github/labels.yml
